### ISSUE TITLE
Composer update vs install

### ISSUE THREAD

**Issue by thijsvdanker** [GIANTCRAB/gitlabby-dockerish-laravel#7]
In your .gitlab-build.sh you're running composer update instead of composer install.
This could result in different outcomes from testing locally vs testing in CI.
Wouldn't it make more sense to use composer install?

Thanks for all the work you've done in putting this together!

**Comment by GIANTCRAB** [comment]
Hello, thank you for raising up this issue. 

Yes, it would make more sense that way. The reason for why it was done this way was because the problem I've faced was network issue. My previous company had very slow network and we had no choice but to install dependencies on Docker build. The composer.lock file was also saved in the Docker image. In order to match the image's installed dependencies with the Git composer.json, composer update was used instead. 

Never really expected more people to be using it. I will be changing this in the future.

**Comment by GIANTCRAB** [comment]
Hello, 

I've applied this change in commit 4a5016f5cf3b629b133d6b8e7a1beb5507d7ec75. The image size has also been decreased. Let me know if there's anything else and feel free to reopen if there's any issue with this.
